# Values used for the deployed application.
service:
  name: delivery-varnish
  # Apply the certificate from content test by default
  certificateAwsArn: "arn:aws:acm:eu-west-1:070529446553:certificate/a6ab3d87-cdae-4db4-838f-3dbce570ad47"
eksCluster: true
elb:
  tags: "systemCode=upp,teamDL=universal.publishing.platform@ft.com,environment=d"

s3:
  enabled: "false"
encryptedsecrets:
  .htpasswd: "AgBH4GJzFE1BrFafPZ39PZlqkDusafrljXOJKBwwUbfPnAq+ns23BPZmThW07tKokyS6+xy4aup2I5SVOMB8AHSjYrJlHkZ5cntqVZg+EFgHodOX1Q/efrHfYCXXmQUZ0IejlnRQrhPBzCZ0BNIUtmaxeSNlwpnFWB67XFYvTcRyIVdQxC7QzGgq2DgQcZ4Pis875DUGxIHVHbeHF2ZASJyUfZtjRrcvYmDl4epDP3jwsZoDI3dho8L01NK7PrG48TdmmgOKA2Hn7b3B9eg9DAFUpWvtovLxoGefsdJVhWcO7Hq80QsCFHI6XoSXwOV4QIbaCkulrzsnPYmkUpYpuLWOZCjBIaL7awsfFlVVRpCQgwH3+GoUKxMEFWW/AUEOuCE55mTF0nbmSSWEabwyySN6qIHKp0YSfWA42V3z2cEiNKSsQw7tI3vOa52dug7Rbipft9uVvTMdCwPMkgufGy2KhO9gbae4DXMRYAuD0mWHEQ66v8uCL9o5kz+k23FCmph/XxCDpcdsOiS0IkXlkcdf8NCzViPb7cIMG3LYgVoQ13PITBQZmAGx6Dj0lPHgqms4syPng+c2uLKuTa78/7qamtf0NWBvCjwdNuA3hQE2YUUQjlivJmBm3c0LrsBthqFB7M5HVwfcfuNQVWj1W5UqNCUm9K4Ke1VyTTo5oK8ZIJEQ/twphLmSenf6SnzCW1zILmHaUcGiYDa45xo7gKpRLG5Emn87nLLp4p8/rGf/U5Uc3WfV5O/RpQI75AupTBVsyZ9vt/5zhlDyJziw+gj5y1L+IVdIeQG1IwbUsJXUQs1MTiIwHEkhiAd3+XBT80t6KmfQZsxDSYFsiRFZKF+Vd2hbZDglnMLFn0vJuqgYX13xXKTwfsd15Zy4TdUVlw=="
