# Default values for delivery-varnish.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "false"
  certificateAwsArn: "" # The ARN of the aws certificate use by the ELB created for this service
  htpasswdSecret: "varnish-auth" # The Kubernetes secret containing the contents of the .htpasswd file used for authentication.
replicaCount: 2
image:
  repository: coco/delivery-varnish
  pullPolicy: IfNotPresent
elbRegistrator:
  image: "coco/coco-elb-dns-registrator:5.1.0"
#resources:
#  limits:
#    memory: 256Mi

